refreshed_utc: "2026-05-09"

monitoring:
  victoria_metrics:
    image: docker.io/victoriametrics/victoria-metrics:v1.142.0
  vmagent:
    image: docker.io/victoriametrics/vmagent:v1.142.0
  grafana:
    image: docker.io/grafana/grafana-oss:13.0.1
  kube_state_metrics:
    image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.18.0

storage:
  local_path_provisioner:
    image: docker.io/rancher/local-path-provisioner:v0.0.36
  busybox:
    image: docker.io/library/busybox:1.37.0

registry:
  oci_distribution:
    image: docker.io/library/registry:3.1.1

dragonfly:
  helm_chart:
    github_release_tag: dragonfly-1.6.26
  images:
    manager:
      image: docker.io/dragonflyoss/manager:v2.4.4-rc.1
    scheduler:
      image: docker.io/dragonflyoss/scheduler:v2.4.4-rc.1
    client:
      image: docker.io/dragonflyoss/client:v1.3.8
    seed_client:
      image: docker.io/dragonflyoss/client:v1.3.8
