apiVersion: v1
kind: Namespace
metadata:
  name: registry-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: registry-system
  labels:
    app.kubernetes.io/name: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-registry
    spec:
      nodeSelector:
        riid.registry: "true"
      containers:
        - name: registry
          image: performance.local_registry
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: local-registry
  namespace: registry-system
  labels:
    app.kubernetes.io/name: local-registry
spec:
  selector:
    app.kubernetes.io/name: local-registry
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
