apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: riid-system
  labels:
    app.kubernetes.io/name: victoria-metrics
spec:
  selector:
    app.kubernetes.io/name: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: riid-system
  labels:
    app.kubernetes.io/name: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoria-metrics
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: riid.monitoring
                    operator: In
                    values: ["true"]
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:latest
          imagePullPolicy: IfNotPresent
          args:
            - -storageDataPath=/victoria-metrics-data
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
          volumeMounts:
            - name: vm-data
              mountPath: /victoria-metrics-data
      volumes:
        - name: vm-data
          emptyDir: {}
