apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: victoria-metrics
    {{- include "riid-observer.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: victoria-metrics
    {{- include "riid-observer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoria-metrics
    spec:
      {{- if .Values.monitoringNodeAffinity.required }}
      affinity:
        {{- include "riid-observer.monitoringAffinity" . | nindent 8 }}
      {{- end }}
      containers:
        - name: victoria-metrics
          image: {{ .Values.victoriaMetrics.image | quote }}
          imagePullPolicy: {{ .Values.victoriaMetrics.pullPolicy }}
          args:
            - -storageDataPath=/victoria-metrics-data
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
          volumeMounts:
            - name: vm-data
              mountPath: /victoria-metrics-data
      volumes:
        - name: vm-data
          emptyDir: {}
