version: 1
provider: dockerhub
refreshed_utc: "2026-05-09"

infra:
  dragonfly:
    helm_chart:
      github_release_tag: dragonfly-1.6.26
  images:
    monitoring.victoria_metrics: docker.io/victoriametrics/victoria-metrics:v1.142.0
    monitoring.vmagent: docker.io/victoriametrics/vmagent:v1.142.0
    monitoring.grafana: docker.io/grafana/grafana-oss:13.0.1
    monitoring.kube_state_metrics: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.18.0
    storage.local_path_provisioner: docker.io/rancher/local-path-provisioner:v0.0.36
    storage.busybox: docker.io/library/busybox:1.37.0
    storage.local_path_provisioner_legacy: docker.io/rancher/local-path-provisioner:v0.0.30
    storage.local_path_helper_busybox: docker.io/library/busybox:latest
    registry.oci_distribution: docker.io/library/registry:3.1.1
    performance.local_registry: docker.io/library/registry:2
    dragonfly.manager: docker.io/dragonflyoss/manager:v2.4.4-rc.1
    dragonfly.scheduler: docker.io/dragonflyoss/scheduler:v2.4.4-rc.1
    dragonfly.client: docker.io/dragonflyoss/client:v1.3.8
    dragonfly.seed_client: docker.io/dragonflyoss/client:v1.3.8
    riid.daemonset.init_busybox: docker.io/library/busybox:1.36.1
    riid.daemonset.riid: ghcr.io/usatovpavel/riid:v0.4.4

test:
  images:
    alpine: docker.io/library/alpine:latest
    amazon-amazon-ecs-agent: docker.io/amazon/amazon-ecs-agent:latest
    amazon-aws-cli: docker.io/amazon/aws-cli:latest
    amazon-aws-efs-csi-driver: docker.io/amazon/aws-efs-csi-driver:master
    amazon-aws-for-fluent-bit: docker.io/amazon/aws-for-fluent-bit:latest
    amazon-aws-xray-daemon: docker.io/amazon/aws-xray-daemon:latest
    amazon-cloudwatch-agent: docker.io/amazon/cloudwatch-agent:latest
    amazonlinux: docker.io/library/amazonlinux:latest
    bitnami-kubectl: docker.io/bitnami/kubectl:latest
    bitnami-mariadb: docker.io/bitnami/mariadb:latest
    bitnami-mongodb: docker.io/bitnami/mongodb:latest
    bitnami-postgresql: docker.io/bitnami/postgresql:latest
    bitnami-redis: docker.io/bitnami/redis:latest
    bitnami-sealed-secrets-controller: docker.io/bitnami/sealed-secrets-controller:latest
    busybox: docker.io/library/busybox:latest
    calico-cni: docker.io/calico/cni:v3.32.0-8-gd0234d1e790f
    calico-node: docker.io/calico/node:v3.33.0-0.dev-472-gcef2f47bb759
    centos: docker.io/library/centos:centos7.9.2009
    cfcommunity-slack-notification-resource: docker.io/cfcommunity/slack-notification-resource:latest
    cimg-android: docker.io/cimg/android:2026.03.1-ndk
    consul: docker.io/library/consul:1.15.4
    containrrr-watchtower: docker.io/containrrr/watchtower:latest
    curlimages-curl: docker.io/curlimages/curl:latest
    debian: docker.io/library/debian:trixie-backports
    docker: docker.io/library/docker:latest
    dynatrace-oneagent: docker.io/dynatrace/oneagent:latest
    elasticsearch: docker.io/library/elasticsearch:9.3.4
    envoyproxy-envoy: docker.io/envoyproxy/envoy:tools-dev-2a8d390f8395e065f19d1dbb74657b8bc59cf030
    fluent-fluent-bit: docker.io/fluent/fluent-bit:latest
    fluent-fluentd-kubernetes-daemonset: docker.io/fluent/fluentd-kubernetes-daemonset:v1.19-debian-kafka-arm64-1
    gitlab-gitlab-runner: docker.io/gitlab/gitlab-runner:bleeding
    golang: docker.io/library/golang:latest
    google-cadvisor: docker.io/google/cadvisor:latest
    grafana-grafana: docker.io/grafana/grafana:latest
    grafana-grafana-image-renderer: docker.io/grafana/grafana-image-renderer:latest
    grafana-loki: docker.io/grafana/loki:main-d8f4d0f
    grafana-promtail: docker.io/grafana/promtail:latest
    hello-world: docker.io/library/hello-world:latest
    httpd: docker.io/library/httpd:latest
    influxdb: docker.io/library/influxdb:latest
    istio-operator: docker.io/istio/operator:1.23.6-distroless
    istio-pilot: docker.io/istio/pilot:1.30.0-beta.0
    istio-proxyv2: docker.io/istio/proxyv2:1.30.0-beta.0
    jenkins-jenkins: docker.io/jenkins/jenkins:latest
    kong-kong-gateway: docker.io/kong/kong-gateway:3.14.0.2-20260428-rhel-fips
    kope-protokube: docker.io/kope/protokube:latest
    linuxserver-faster-whisper: docker.io/linuxserver/faster-whisper:3.1.0-gpu
    linuxserver-jackett: docker.io/linuxserver/jackett:latest
    linuxserver-nzbget: docker.io/linuxserver/nzbget:latest
    linuxserver-ombi: docker.io/linuxserver/ombi:latest
    linuxserver-plex: docker.io/linuxserver/plex:latest
    linuxserver-radarr: docker.io/linuxserver/radarr:6.2.0-nightly
    linuxserver-sonarr: docker.io/linuxserver/sonarr:latest
    linuxserver-tautulli: docker.io/linuxserver/tautulli:latest
    ljfranklin-terraform-resource: docker.io/ljfranklin/terraform-resource:latest
    mariadb: docker.io/library/mariadb:lts-ubi9
    memcached: docker.io/library/memcached:latest
    moby-buildkit: docker.io/moby/buildkit:latest
    mysql: docker.io/library/mysql:latest
    newrelic-infrastructure-bundle: docker.io/newrelic/infrastructure-bundle:latest
    newrelic-newrelic-fluentbit-output: docker.io/newrelic/newrelic-fluentbit-output:latest
    newrelic-nri-kube-events: docker.io/newrelic/nri-kube-events:latest
    newrelic-nri-kubernetes: docker.io/newrelic/nri-kubernetes:latest
    nextcloud: docker.io/library/nextcloud:latest
    nginx: docker.io/library/nginx:trixie-perl
    nginxinc-nginx-unprivileged: docker.io/nginxinc/nginx-unprivileged:alpine3.23-perl
    node: docker.io/library/node:latest
    ollama-ollama: docker.io/ollama/ollama:rocm
    openpolicyagent-gatekeeper: docker.io/openpolicyagent/gatekeeper:dev
    percona-percona-xtradb-cluster-operator: docker.io/percona/percona-xtradb-cluster-operator:1.19.1-community-bundle
    php: docker.io/library/php:8.4.21RC1-zts-trixie
    pivotalcf-pivnet-resource: docker.io/pivotalcf/pivnet-resource:latest
    portainer-agent: docker.io/portainer/agent:alpine-sts
    portainer-portainer: docker.io/portainer/portainer:latest
    portainer-portainer-ce: docker.io/portainer/portainer-ce:alpine-sts
    postgres: docker.io/library/postgres:latest
    presearch-node: docker.io/presearch/node:latest
    prom-node-exporter: docker.io/prom/node-exporter:latest
    prom-prometheus: docker.io/prom/prometheus:latest
    python: docker.io/library/python:latest
    pytorch-almalinux-builder: docker.io/pytorch/almalinux-builder:cuda13.2-44c38d967b9e69e8191c1ecbf5b67f890584f8a3
    pytorch-pytorch: docker.io/pytorch/pytorch:2.11.0-cuda12.8-cudnn9-devel
    pytorch-torchserve: docker.io/pytorch/torchserve:0.12.0-cpp-dev-gpu
    rabbitmq: docker.io/library/rabbitmq:latest
    rancher-mirrored-pause: docker.io/rancher/mirrored-pause:3.9
    rancher-rancher-agent: docker.io/rancher/rancher-agent:head
    redis: docker.io/library/redis:latest
    registry: docker.io/library/registry:latest
    ruby: docker.io/library/ruby:latest
    seabreeze-dumpsettingsandenvvariables: docker.io/seabreeze/dumpsettingsandenvvariables:linuxv4
    sonarqube: docker.io/library/sonarqube:latest
    stakater-reloader: docker.io/stakater/reloader:merge-1138-ubi
    timberio-vector: docker.io/timberio/vector:nightly-distroless-libc
    tomcat: docker.io/library/tomcat:jre25-temurin-noble
    ubuntu: docker.io/library/ubuntu:latest
    v2tec-watchtower: docker.io/v2tec/watchtower:latest
    wordpress: docker.io/library/wordpress:php8.5-fpm