manager:
  addr: "http://dfmanager:65003"

scheduler:
  announceInterval: 10s
  scheduleTimeout: 3h
  enableBackToSource: true

host:
  hostname: "dfdaemon1"

server:
  cacheDir: .dragonfly/cache

storage:
  dir: .dragonfly/data
  server:
    tcpPort: 65015
    quicPort: 65016

download:
  server:
    socketPath: /tmp/dfdaemon1.sock
  protocol: tcp
  concurrentPieceCount: 8
  pieceTimeout: 30s

upload:
  server:
    port: 4001

proxy:
  server:
    port: 65011

metrics:
  server:
    port: 65012

health:
  server:
    port: 65013

stats:
  server:
    port: 65014

gc:
  interval: 3600s
  policy:
    taskTTL: 720h
    persistentTaskTTL: 720h
    persistentCacheTaskTTL: 720h
