#!/usr/bin/env bash
# Зеркалирует 30 образов FIRST_30_REPOSITORIES (performance-тесты) в приватный реестр.
# Список читается из PopularDockerHubImagesFromProgramDocs.java — единый источник с тестами.
#
# REGISTRY в .env:
#   - только ID реестра Selectel: 2d731864-81c8-...  → push в cr.selcloud.ru/<ID>/...
#   - полный префикс: cr.selcloud.ru/<ID> или другой.host/проект
# Опционально REGISTRY_LOGIN_HOST, если без «/» указан не Selectel (по умолчанию cr.selcloud.ru).
#
# Selectel: в доке лимит длины имени образа; пути вида library/hello-seattle (21 символ) реестр отклоняет
# (docker push после ретраев: unknown:). Для *selcloud.ru по умолчанию push идёт без префикса library/:
#   cr.selcloud.ru/<id>/hello-seattle:latest
# После успешного зеркала пишется performance-registry-smoke-map.tsv (эта папка): Docker Hub repo → RIID repository.
# Смок: make smoke-download со SMOKE_REGISTRY_TARGET=selectel использует этот файл (или см. smoke-resolve-repository.sh).
# Отключить strip library/: REGISTRY_PUSH_REPO_STRIP_LIBRARY=0
#
# library/clefos: на Docker Hub нет манифеста linux/amd64 — pull падает; в Java тоже исключён из SCENARIO_C_WARM.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DIR/../../../.." && pwd)"
ENV_FILE="${1:-$DIR/../.env}"
JAVA_LIST="$REPO_ROOT/src/testFixtures/java/riid/config/PopularDockerHubImagesFromProgramDocs.java"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "init-performance-registry-images: нет $ENV_FILE (задайте путь: $0 /path/.env)" >&2
  exit 1
fi
if [[ ! -f "$JAVA_LIST" ]]; then
  echo "init-performance-registry-images: не найден $JAVA_LIST" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${REGISTRY_USER:?в $ENV_FILE должен быть REGISTRY_USER}"
: "${REGISTRY_PASSWORD:?в $ENV_FILE должен быть REGISTRY_PASSWORD}"
: "${REGISTRY:?в $ENV_FILE должен быть REGISTRY (см. комментарий в шапке скрипта)}"

REGISTRY="${REGISTRY%/}"
# Полный префикс push: cr.selcloud.ru/<id> или свой host/проект.
# Только UUID/имя без «/» (как в панели Selectel) → подставляем cr.selcloud.ru/
if [[ "$REGISTRY" == */* ]]; then
  REG_PREFIX="$REGISTRY"
  REG_HOST="${REGISTRY%%/*}"
else
  REG_HOST="${REGISTRY_LOGIN_HOST:-cr.selcloud.ru}"
  REG_PREFIX="${REG_HOST}/${REGISTRY}"
fi
# Путь репозитория под REG_HOST (для RIID POST /pull при профиле registry-selectel): <id>/jobber и т.д.
_host_slash="${REG_HOST}/"
REG_REPO_PREFIX="${REG_PREFIX#"$_host_slash"}"

if [[ -z "${REGISTRY_PUSH_REPO_STRIP_LIBRARY:-}" ]]; then
  if [[ "$REG_HOST" == *selcloud.ru ]]; then
    REGISTRY_PUSH_REPO_STRIP_LIBRARY=1
  else
    REGISTRY_PUSH_REPO_STRIP_LIBRARY=0
  fi
fi

REF="$(grep -E '^\s*public static final String POPULAR_IMAGES_REFERENCE' "$JAVA_LIST" | sed -n 's/.*= *"\([^"]*\)".*/\1/p')"
[[ -n "$REF" ]] || REF="latest"

mapfile -t REPOS < <(grep -E '^\s+"library/' "$JAVA_LIST" | sed -n 's/.*"\(library\/[^"]*\)".*/\1/p')
if [[ "${#REPOS[@]}" -ne 30 ]]; then
  echo "init-performance-registry-images: ожидалось 30 репозиториев в $JAVA_LIST, получено ${#REPOS[@]}" >&2
  exit 1
fi

echo ">>> docker login $REG_HOST" >&2
echo "$REGISTRY_PASSWORD" | docker login "$REG_HOST" --username "$REGISTRY_USER" --password-stdin

n_done=0
for repo in "${REPOS[@]}"; do
  if [[ "$repo" == library/clefos ]]; then
    echo ">>> skip: $repo (нет linux/amd64 в Docker Hub)" >&2
    continue
  fi
  push_repo="$repo"
  if [[ "$REGISTRY_PUSH_REPO_STRIP_LIBRARY" == 1 ]] && [[ "$repo" == library/* ]]; then
    push_repo="${repo#library/}"
  fi
  src="docker.io/${repo}:${REF}"
  dst="${REG_PREFIX}/${push_repo}:${REF}"
  echo ">>> pull  $src" >&2
  docker pull "$src"
  echo ">>> tag+push $dst" >&2
  docker tag "$src" "$dst"
  docker push "$dst"
  n_done=$((n_done + 1))
done

emit_performance_registry_smoke_map() {
  echo "# Generated by init-performance-registry-images.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
  echo "# tag (POPULAR_IMAGES_REFERENCE): $REF"
  echo "# REG_HOST=$REG_HOST  REG_PREFIX=$REG_PREFIX"
  echo "# Columns: docker_hub_repository<TAB>riid_repository (path for configured registry host)"
  local repo push_repo riid_repo
  for repo in "${REPOS[@]}"; do
    if [[ "$repo" == library/clefos ]]; then
      echo "# library/clefos — not mirrored (no linux/amd64 manifest on Docker Hub)"
      continue
    fi
    push_repo="$repo"
    if [[ "$REGISTRY_PUSH_REPO_STRIP_LIBRARY" == 1 ]] && [[ "$repo" == library/* ]]; then
      push_repo="${repo#library/}"
    fi
    if [[ -n "$REG_REPO_PREFIX" ]]; then
      riid_repo="${REG_REPO_PREFIX}/${push_repo}"
    else
      riid_repo="$push_repo"
    fi
    printf '%s\t%s\n' "$repo" "$riid_repo"
  done
}

MAP_OUT="$DIR/performance-registry-smoke-map.tsv"
emit_performance_registry_smoke_map > "$MAP_OUT"
echo ">>> smoke map (Docker Hub name to RIID repository on mirror): $MAP_OUT" >&2

echo ">>> готово: $n_done образов в $REG_PREFIX (всего в списке ${#REPOS[@]}, пропущено $(( ${#REPOS[@]} - n_done )))" >&2
